// <auto-generated />
namespace technical__test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class DateDateModificationDateChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateDateModificationDateChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202509032106127_DateDateModificationDateChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
